apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager

commonLabels:
  app: cert-manager
  managedBy: argocd
  managementCodeGroup: chrismlee42-dev
  managementCodeProject: cert-manager-config

resources:
  - namespace.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml
