apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-config

commonLabels:
  app: cert-manager
  managedBy: argocd
  managementCodeGroup: chrismlee42-dev
  managementCodeProject: cert-manager-config

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml
  - letsencrypt-prod-clusterissuer.yaml
  - letsencrypt-prod-issuer.yaml
  - letsencrypt-staging-clusterissuer.yaml
  - letsencrypt-staging-issuer.yaml
  - namespace.yaml
  - self-signed-ca-clusterissuer.yaml
  - self-signed-ca-certificate.yaml
  - self-signed-clusterissuer.yaml
  - self-signed-issuer.yaml
