apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # Email address used for ACME registration
    email: chrismlee42+letsencrypt-chris-pc@gmail.com
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-issuer
    solvers:
      - dns01:
          webhook:
            solverName: he
            groupName: cert-manager.chris-pc.clee.private.morphacy.net
            config:
              heUrl: https://dns.he.net
              method: login
              credentialsSecretRef:
                name: he-credentials
        selector:
          dnsZones:
            - morphacy.net
